---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volume-cleaner
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pv"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pvc"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volume-cleaner-bind
subjects:
  - kind: ServiceAccount
    name: volume-cleaner
    namespace: das
roleRef:
  kind: ClusterRole
  name: volume-cleaner
  apiGroup: rbac.authorization.k8s.io
