---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-cleaner-controller
  namespace: das
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-cleaner-controller
  template:
    metadata:
      labels:
        app: volume-cleaner-controller
    spec:
      serviceAccountName: volume-cleaner
      containers:
        - name: volume-cleaner
          image: controller
          imagePullPolicy: Never
          command: ["/volume-cleaner-controller"]
          envFrom:
            - configMapRef:
                name: volume-cleaner-controller-config
      restartPolicy: Always
