---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts1
  namespace: anray-liu
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-container
          image: busybox
          command: ["sleep", "3600"]
          volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc1
