---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: volume-cleaner-scheduler-egress
  namespace: das
spec:
  podSelector:
    matchLabels:
      app: volume-cleaner-scheduler
  egress:
    - to:
      # ips for https://api.notification.canada.ca/v2/notifications/email
      - ipBlock:
          cidr: 16.52.61.217/32
      - ipBlock:
          cidr: 15.222.139.116/32
      - ipBlock:
          cidr: 15.223.249.191/32
      ports:
      - protocol: TCP
        port: 443

  policyTypes:
    - Egress
