---
apiVersion: batch/v1
kind: Job
metadata:
  name: volume-cleaner-dry-run
  namespace: das
  labels:
    app: volume-cleaner
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: volume-cleaner
    spec:
      serviceAccountName: volume-cleaner
      containers:
        - name: cleaner
          image: artifactory.cloud.statcan.ca/das-aaw-docker/volume-cleaner:latest
          command: ["/volume-cleaner", "-dry-run"]
          envFrom:
            - configMapRef:
                name: volume-cleaner-dry-run-config
      restartPolicy: Never
