---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: volume-cleaner-scheduler
  namespace: das
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: volume-cleaner-scheduler
        spec:
          serviceAccountName: volume-cleaner
          containers:
            - name: cleaner
              image: docker.io/statcan/volume-cleaner-scheduler:latest
              command: ["/volume-cleaner-scheduler"]
              envFrom:
                - configMapRef:
                    name: volume-cleaner-scheduler-config
                - secretRef:
                    name: volume-cleaner-scheduler-secret
          restartPolicy: Never
