---
apiVersion: v1
kind: Secret
metadata:
  name: volume-cleaner-scheduler-secret
  namespace: das
type: Opaque
data:
  API_KEY: "dGVzdA=="             # test
  EMAIL_TEMPLATE_ID: "dGVzdA=="   # test
