---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-cleaner-scheduler-config
  namespace: das
data:
  NAMESPACE: "anray-liu"
  TIME_LABEL: "volume-cleaner/unattached-time"
  NOTIF_LABEL: "volume-cleaner/notification-count"
  GRACE_PERIOD: "5"
  TIME_FORMAT: "2006-01-02_15-04-05Z"
  DRY_RUN: "false"
  NOTIF_TIMES: "1, 2, 3, 4"
  BASE_URL: "https://api.notification.canada.ca"
  ENDPOINT: "/v2/notifications/email"
