---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-cleaner-scheduler-config
  namespace: zone
data:
  NAMESPACE: ""
  TIME_LABEL: "volume-cleaner/unattached-time"
  NOTIF_LABEL: "volume-cleaner/notification-count"
  IGNORE_LABEL: "volume-cleaner/ignore"
  GRACE_PERIOD: "3"
  TIME_FORMAT: "2006-01-02_15-04-05Z"
  DRY_RUN: "true"
  NOTIF_TIMES: "1, 2, 3"
  BASE_URL: "https://api.notification.canada.ca"
  ENDPOINT: "/v2/notifications/email"
