---
name: CI Pipeline

on: [push, pull_request]

env:
  REGISTRY: k8scc01covidacr.azurecr.io

jobs:

  integration-test:
    name: Golang Tests
    runs-on: ubuntu-latest
    steps:
      # allows workflow to access the repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with: 
          registry: true
          registry_port: 5050

      - run: |
          docker build --progress=plain --no-cache -t localhost:5050/controller:test -f docker/controller/Dockerfile ..
          # docker build --progress=plain --no-cache -t localhost:5050/scheduler:test -f docker/scheduler/Dockerfile ..
          docker push localhost:5050/controller:test

      - run: |
          kind load docker-image localhost:5050/controller:test
          # kind load docker-image localhost:5050/scheduler:test

      - run: |
          kubectl apply -f testing/manifests.yaml
          kubectl apply -f manifests/rbac.yaml \
            -f manifests/serviceaccount.yaml \
            -f manifests/netpol.yaml \
            -f manifests/controller/controller_config.yaml
          kubectl apply -f testing/controller_deployment.yaml
          sleep 10
          kubectl get pod -l app=volume-cleaner-controller -o yaml -n das
          kubectl logs -l app=volume-cleaner-controller -n das
