---
name: CI Pipeline

on: [push, pull_request]

env:
  REGISTRY: k8scc01covidacr.azurecr.io

jobs:

  integration-test:
    name: Golang Tests
    runs-on: ubuntu-latest
    steps:
      # allows workflow to access the repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - run: |
          kubectl apply -f testing/manifests.yaml
          make run_controller
          sleep 10
          kubectl get pod -n das
  