---
name: CI Nightly Scans 

on:
  # Schedule the workflow to run every day at 7:00 AM UTC (3:00 AM EDT)
  schedule:
    - cron: '0 7 * * *' # min hour day-of-month month day-of-week

  # Allows you to manually trigger the workflow from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  nightly-trivy-scan:
    name: Trivy Scans
    uses: ./.github/workflows/trivy-scan.yaml
    secrets: inherit
