---
name: CI Pipeline

on: [push, pull_request]

env:
  REGISTRY: k8scc01covidacr.azurecr.io
  GO_VERSION: 1.24

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Lint YAML
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run yamllint
        run: |
          pip install yamllint
          yamllint ./docker/controller/.Dockerfile ./docker/scheduler/.Dockerfile

  build-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          file: ./cmd/controller/.Dockerfile
          tags: ${{ env.REGISTRY }}/volume-cleaner-controller:latest
          push: true

      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/volume-cleaner-controller:latest
          severity: "CRITICAL"
          ignore-unfixed: true
          exit-code: 1
          format: table
