---
name: CI Trivy Scans

on:
  workflow_call:
    inputs:
      verticals:
        required: true
        type: string

env:
  REGISTRY: docker.io

jobs:
  # Deep Docker Image Vulnerability Scanning
  docker-vulnerability-scan:
    name: Trivy Vulnerability Scan for ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ${{ fromJSON(inputs.verticals) }}

    steps:
      # allows workflow to access the repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Security Scan Image ${{ matrix.image }}
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: ${{ env.REGISTRY }}/statcan/volume-cleaner-${{ matrix.image }}:latest
          severity: "CRITICAL"
          ignore-unfixed: true
          exit-code: 1  # Fail the job if critical unfixed vulnerabilities are found
